# 다수의 테이블 제어하기

## 데이터 그룹 짓기

### 데이터를 그룹화한다면?

회원들이 책을 몇 번 대여했는지 어떻게 알 수 있을까?

### GROUP BY

```sql
SELECT user_id, COUNT(*)
FROM rental
GROUP BY user_id;
```

- group by를 더 잘 활용하려면
  - 앞서 배운 sum, avg, count, max, min을 활용


```sql
SELECT user_id, SUM(컬럼명) FROM rental GROUP BY user_id;
SELECT user_id, AVG(컬럼명) FROM rental GROUP BY user_id;
SELECT user_id, MAX(컬럼명) FROM rental GROUP BY user_id;
SELECT user_id, MIN(컬럼명) FROM rental GROUP BY user_id;
```

## 데이터 그룹에 조건 적용하기

### GROUP BY 절에 조건을 부여하고 싶다면?

어떻게 해야 책을 2번 이상 대여한 사람만 조회 할 수 있을까?

### GROUP BY/ HAVING 절의 기본 문법

```sql
SELECT user_id, COUNT(*)
FROM rental
GROUP BY user_id
HAVING COUNT(user_id) > 1;
```
rental 테이블에서 user_id가 같은 1개 초과의 데이터가 몇 개 있는지 검색

## 두개의 테이블에서 조회하기

### 여러 테이블의 정보를 한번에 조회한다면?

어떻게 도도새가 필요한 데이터를 한 번에 조회할 수 있을까?

### INNER JOIN

```sql
SELECT *
FROM rental
INNER JOIN user;
```

## 조건을 적용해 두개의 테이블 조회하기

### JOIN 에 조건을 적용하려면?

회원 정보에 저장된 id와 일치하는 값들만 조회하고자 한다.

### INNER JOIN / ON 문의 기본 문법

```sql
SELECT *
FROM rental
INNER JOIN user
ON user.id = rental.user_id;
```

## LEFT JOIN

### 왼쪽 테이블의 모든 값을 포함하여 연결하기

```sql
SELECT *
FROM user
LEFT JOIN rental
ON user.id = rental.user_id;
```

user 테이블을 모두 출력하되 모든 user테이블의 user_id와 rental테이블의 id가 겹치도록 합친다.

## RIGHT JOIN

### 오른쪽 테이블의 모든 값을 포함하여 연결하기

```sql
SELECT *
FROM user
RIGHT JOIN rental
ON user.id = rental.user_id;
```

rental 테이블을 모두 출력하되 모든 rental 테이블의 user_id와 user 테이블의 id가 겹치도록 합친다.

# 서브쿼리

## 서브쿼리

### 서브쿼리 정의

하나의 쿼리 안에 포함된 또 하나의 쿼리 메인 쿼리가 서브쿼리를 포함하는 종속적인 관계

### 서브쿼리의 특징

- 알려지지 않은 기준을 이용한 검색에 유용
- 메인 쿼리가 실행되기 이전에 한 번만 실행
- 한 문장에서 여러 번 사용 가능

### 서브쿼리를 사용한 예시

```sql
SELECT * 
FROM employee
WHERE 급여 >
    (SELECT 급여 FROM employee WHERE 이름='elice');
```

사원 elice의 급여를 알지 못해도 검색 가능

### 서브쿼리 사용시 주의사항

1. 서브쿼리는 괄호와 함께 사용되어야 한다.
2. 서브쿼리 안에서 ORDER BY 절은 사용할 수 없다.
3. 서브쿼리는 연산자의 오른쪽에 사용되어야 한다.
4. 서브쿼리는 오로지 SELECT 문으로만 작성할 수 있다.

## 반환에 따른 분류

### 단일 행 서브쿼리 정의

결과가 한 행만 나오는 서브쿼리

서브쿼리가 결과를 1개의 값만 반환하고, 이 결과를 메인쿼리로 전달하는 쿼리

```sql
SELECT *
FROM employee
WHERE 급여 >
    (SELECT 급여 FROM employee WHERE 사원번호 = 1);
```

사원번호는 기본적으로 1개만 있으므로 한 개의 행만 반환함 = 단일 행

### 다중 행 서브쿼리 정의

결과가 한 행만 나오는 단일 행 서브쿼리와는 다르게 서브쿼리가 결과를 2개 이상 반환하고, 이 결과를 메인쿼리로 전달하는 쿼리

### 다중 행 서브쿼리 기본 문법

```sql
SELECT *
FROM employee
WHERE 급여 
IN (SELECT max(급여) FROM employee GROUP BY 부서번호);
```

### 다중 행 연산자

| 기호  |     뜻     |
| :---: |   :---:    |
|   IN  | 하나라도 만족하면 반환 |
|  ANY  | 하나라도 만족하면 반환, 비교 연산 가능 |
|  ALL  | 모두 만족하면 반환, 비교 연산 가능 | 

### 다중 행 연산자 사용 예시

```sql
1 in (1, 2, 3, 4) -- 참
10 <any (1, 2, 3, 4)    -- 거짓
99 >=all (99, 100, 101) -- 거짓
```

## 위치에 따른 분류

### 일반적인 서브쿼리의 형태

```sql
SELECT * FROM employee
WHERE 급여 >
    (SELECT 급여 FROM employee WHERE 이름='elice');
```

### 스칼라 서브쿼리 정의

SELECT 절에서 사용하는 서브쿼리

스칼라 서브쿼리는 오로지 한 행만 반환, 마치 JOIN을 사용한 것과 같은 결과를 나타낸다.

### 스칼라 서브쿼리 사용 방법

```sql
SELECT students.name, (
    SELECT math
    FROM middle_test as m
    WHERE m.student_id = students.student_id
) AS middle_avg
FROM students;
```

# 데이터베이스 준비하기

## 데이터베이스란?

데이터베이스란 공유하여 사용할 목적으로 체계화하여 관리하는 데이터의 집합

|   |관계형 데이터베이스(RDB)|비관계형 데이터베이스(NoSQL)|
|   :---:         |        :---:        |  :---:          | 
|각 테이블 간 관계|   O                 |   X             |
|     스키마      |   O                 |   X             |
|   |구조적으로 안정적이나 유연하지 못함|유연성을 가지고 있으나 구조 결정이 어려움|
- 상황과 조건에 맞춰 적절한 데이터베이스를 선택하는 것이 중요!

## 데이터모델링이란?

효율적으로 데이터베이스를 구축하기 위해 데이터베이스의 뼈대를 세우는 작업

- 요구 사항 정리
  - 데이터가 어떠한 형태, 어떤 목적을 가지고 있는지 정리

- 개념적 데이터 모델 설계
  - 핵심 개체를 찾고, 각 개체 간의 관계를 정리

- 논리적 데이터 모델 설계
  - 실제 데이터베이스로 구현하기 위한 모델링

- 물리적 데이터 모델 설계
  - 데이터가 어떻게 컴퓨터에 저장될 지 설계

## 코더랜드 공유 킥보드 사업 소개

- 엘리스 토끼의 야심 찬 사업 계혹
  - "코더랜드 공유 킥보드 사업"

- 사업을 운영하기 위해서는 어떤 정보가 필요할까?
  - 킥보드를 관리하기 위한 정보
  - 고객을 관리하기 위한 정보
  - 대여 기록을 관리하기 위한 정보

사업을 운영하기 전 필요한 정보와 내용을 알아보자

### 코더랜드 공유 킥보드 운영 방침 : 대여

1. 원활한 대여 관리를 위해 대여 정보는 대여한 킥보드의 ID, 대여한 고객의 ID, 대여해간 날짜로 구성된다.
2. 대여한 킥보드의 ID 는 실제 운영(소유)하고 있는 킥보드 ID(영문 + 숫자 조합으로 3자리)만 입력 될 수 있다.
3. 대여한 고객의 ID는 실제 가입한 고객의 ID(영문 + 숫자 조합으로 15자리 미만)만 입력 될 수 있다.
4. 대여 일자는 년-월-일 시:분(YYYY-MM-DD HH:MM)으로 입력되며 고객은 킥보드 대여 후 1분 이내 다시 대여할 수 없다.
   - 단, 고객이 대여할 수 있는 킥보드의 대수에는 제한이 없다.

### 코더랜드 공유 킥보드 운영 방침 : 킥보드

1. 킥보드 관리를 위해 모든 킥보드는 ID, 이미지 정보, 종류 정보, 연식 정보를 가지고 있다.
2. 킥보드의 ID는 중복이 되거나 수정 할 수 없다.
3. 킥보드의 이미지는 50자 미만의 URL로 구성되어 있으며 연식과 종류가 같은 킥보드일 경우 동일한 이미지를 활용한다.
4. 킥보드의 종류는 브레이크의 위치에 따라 두가지(뒷바퀴에 위치 - A형, 핸들에 위치 - B형)로 구분되며 중복이 가능하다.
5. 킥보드의 연식은 킥보드의 생산년도로 4자리 숫자(YYYY) 로 표현되며 중복이 가능하다.

### 코더랜드 공유 킥보드 운영 방침 : 고객

1. 고객 관리를 위해 모든 고객은 ID, 이름, 전화번호를 가지고 있다.
2. 고객 ID는 영문 + 숫자로 조합되며 길이는 15자 미만으로 구성되어 있다. 또한 ID는 중복이 되거나 수정 될 수 없다.
3. 고객의 이름은 10자 미만의 한글로 구성되어 있으며 동명이인을 고려하여 중복이 가능하다.
4. 고객의 전화번호는 15자 미만의 문자(`***-****-****`)로 구성되어 있다.
5. 대여 증인 킥보드가 없어야 회원 탈퇴(고객 정보 삭제)가 가능하다.

## 데이터베이스 네이밍 규칙

유지보수와 의미의 명확성을 전달하기 위해 네이밍 규칙을 설정

### 공통 규칙

1. 줄임말 사용은 최소화한다. (단, 사용할 경우 범용적으로 사용되는 줄임말을 사용한다.)
   - kb_image(x) -> kickboard_image(O)
   - tb_KickboardInfo(삼각형)

### 테이블 네이밍 규칙

1. 테이블 명을 작성할 때는 파스칼 표기법을 사용 한다.
  - kickboard_rental (X) -> KickboardRental (O)
  - customer_info(X) -> CustomerInfo(O)

2. 테이블, 뷰(View)임을 한 눈에 확인 할 수 있도록 테이블 명 앞에는 `tb_`, `v_`를 붙인다.
  - tb_KickboardRental (킥보드 대여와 관련된 체이블)
  - v_KickboardInfoForAnalysis(데이터 분석을 위해 필요한 정보만 모다 둔 가상 테이블)

### 속성 네이밍 규칙

1. 속성 명을 작성할 때는 스네이크 표기법을 활용한다.
  - customerID(X) -> customer_id(O)
  - CustomerTel(X) -> customer_tel(O)

2. 유일키, 외래키 등은 한 눈에 알아 볼 수 있도록 속성 명 앞에 `pk_`, `fk_`를 붙인다.
  - (단, 중복으로 설정되어 있는 경우 외래키 > 유일키 순으로 작성한다.)
  - pk_kickboard_id
  - fk_pk_customer_id 

## 유일키란?

### KEY

데이터베이스에서 튜플(레코드, 행) 간 구분을 위한 값(속성)

- 유일키, 복합키, 외래키 등 다양한 종류가 존재

### 유일키 (Primary Key) 선언하기

```sql
CREATE TABLE '테이블 명'{
  '속성명' 타입,
  '속성명' 타입,
  ...
  PRIMARY KEY('유일키로 사용할 속성 명')
}
```

## 복합키란?

### 복합키 (Composite Key)

두 개 이상의 속성을 활용하여 튜플(레코드, 행)을 구분지어주는 방법

### 복합키 선언하기

```sql
CREATE TABLE '테이블 명'{
  '속성명' 타입,
  '속성명' 타입,
  ...
  PRIMARY KEY('복합키로 사용할 속성 명', '복합키로 사용할 속성 명')
}
```

## 외래키란?

### 외래키(Foreign Key)

다른 테이블의 키와 연결을 해주는 키이며, 참조의 무결성을 유지하기 위해 활용
- 참조의 무결성: 외리키 값이 참조 중인 테이블의 값과 일관성을 가지는 것을 의미
```sql

CREATE TABLE '테이블 명'{
  '속성명' 타입,
  '속성명' 타입,
  ...
  FOREIGN KEY(`외래키로 사용할 속성 명`) REFERENCES `참조하는 속성이 있는 테이블`(`참조할 속성 명`)
```

# 정규화

## 정규화란

테이블 간 데이터 조작(삽입, 수정, 삭제)시 발생 할 수 있는 이상 현상을 줄이기 위해 하는 작업

## 1차 정규화

### 1차 정규화(1NF)란?

각 속성 마다 값이 1개씩 존재하도록 하는 과정(원자화)

![](image/029_001.png)
![](image/029_002.png)

## 2차 정규화

### 2차 정규화(2NF)란?

복합키로 구성 되어있을 때 고려해야하며

모든 속성이 완전 함수 종속이 되도록 하는 작업

- 완전 함수 종속
  - A, B, C, D가 있을 때 B가 A에 의해 종속되는 경우 B는 다른 내용(C, D)에 의해 종속이 되지 않는 경우

![](image/029_003.png)

고객 이름과 전화번호는 고객의 ID에 종속되어 있음
이 두 속성을 대여 테이블로부터 분리시켜 종속성을 제거

![](image/029_004.png)

## 3차 정규화

테이블 내에서 이행적 요소를 제거하는 작업

![](image/029_005.png)

# View

## View란?

하나 이상의 테이블에서 여러 정보를 토대로 만들어지는 가상의 테이블

고객이 킥보드를 빌리려고 할 때 어떤 정보(테이블)을 보여줘야 할까?
- 킥보드 정보를 담고 있는 kickboardinfo 테이블
  - 킥보드 고유 ID
  - 킥보드 타입
  - 킥보드 연식

고객이 킥보드를 대여하는 불필요한 요소까지 포함되어 있음

킥보드 테이블에서 필요한 정보만 추출하여 가상의 테이블 생성

고객에게는 킥보드 가상 테이블을 제공, 보안성과 속도를 높일 수 있음

### 뷰(View) 생성 방법

```sql
CREATE VIEW `테이블 명` AS
SELECT 가져오고자 할 속성 명, 속성 2...
FROM 가져오고자 할 속성이 있는 테이블
(WHERE 등 사용 가능)
```

## 여러 테이블에서 View 활용

코더랜드 공유 킥보드 사업을 시작한지 일주일이 지났어요!

데이터 분석팀의 도도새는 지난 일주일의 정보를 토대로 고객들이 어떤 킥보드를 선호하는지 분석을 해보려고 합니다.

도도새는 데이터 분석을 위해 엘리스 토끼에게 아래의 자료 요청했어요.

- 대여일자
- 킥보드 종류
- 킥보드 연식

![](image/029_006.png)

- View를 생성하여 제공?
  - 필요한 정봄만 선택해 가상의 테이블로 제공, 불필요한 정보 및 고객 정보를 제외하여 제공 할 수 있음

```sql
CREATE VIEW `테이블 명` AS
SELECT 가져오고자 할 속성 명, 속성 2 ...
FROM 가져오고자 할 속성이 있는 테이블, 테이블2 ...
(WHERE 등 사용 가능)
```

## view 삭제

데이터 분석팀의 도도새가 데이터분석이 완료되었다고 합니다.

### View는 실제 존재하지 않는 가상의 테이블

- 해당 테이블을 삭제하더라도 원본 테이블에는 영향 X

```sql
DROP VIEW 삭제하고자 하는 view 명
```